[[structs]]
name = "Velocity"
component = true
fields = [
    {name = "value", type = "vec2"},
]

[[structs]]
name = "PlayerInputState"
component = true
fields = [
    {name = "moveDir", type = "vec2"},
]

[[structs]]
name = "RectangleRender"
component = true
fields = [
    {name = "size", type = "vec2"}
]